language: php
sudo: false
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - composer self-update
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master

install:
  - travis_retry composer update -n --prefer-dist --prefer-stable

script:
  - ./vendor/bin/phpunit -v

jobs:
  include:
    # Tests the lowest set of dependencies
    - php: 7.1
      env: LOWEST
      install:
        - travis_retry composer update -n --prefer-lowest --prefer-stable --prefer-dist

    # Test against latest Symfony 4.3 stable
    - php: 7.3
      env: SYMFONY_REQUIRE="4.3.*"
      install:
        - composer require --dev symfony/mailer --no-update
        - travis_retry composer update -n --prefer-dist --prefer-stable

    # Test against latest Symfony 4.4 stable
    - php: 7.3
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - composer require --dev symfony/mailer --no-update
        - travis_retry composer update -n --prefer-dist --prefer-stable

    # Test against latest Symfony 5.0 stable
    - php: 7.3
      env: SYMFONY_REQUIRE="5.0.*"
      install:
        - composer require --dev symfony/mailer --no-update
        - travis_retry composer update -n --prefer-dist --prefer-stable

    - stage: Code Quality
      php: 7.3
      script:
        - ./vendor/bin/php-cs-fixer fix -v --dry-run

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
