language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DEPENDENCIES="symfony/lts:^3";COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: DEPENDENCIES="symfony/lts:^3"

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [ "$DEPENDENCIES" != "" ]; then composer require --no-update $DEPENDENCIES; fi;
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi

install: travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
