language: php
sudo: required
dist: trusty
group: edge
php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=3.4.*

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.1.*
    - php: 7.3
      env: SYMFONY_VERSION=4.2.*
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: travis_wait composer update --prefer-source $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
